name: Build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        documents:
          - proposal

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Build documents using LaTeX (${{ matrix.documents }})
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_lualatex: true
          root_file: ${{ matrix.documents }}/main.tex
          extra_fonts: |
            ../fonts/*.ttf

      - name: Upload build assets (${{ matrix.documents }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.documents }}.pdf
          path: src/${{ matrix.documents }}.pdf

