name: release
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        documents:
          - proposal

    steps:
      - uses: actions/checkout@v2

      - name: Build documents using LaTeX (${{ matrix.documents }})
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: src
          latexmk_use_lualatex: true
          root_file: ${{ matrix.documents }}/main.tex
          extra_fonts: |
            ../fonts/*.ttf

      - name: Rename PDF output (${{ matrix.documents }})
        run: mv src/main.pdf src/${{ matrix.documents }}.pdf 

      - name: Upload build assets (${{ matrix.documents }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.documents }}
          path: src/${{ matrix.documents }}.pdf

  pre-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          name: Latest Build
          files: ./artifacts/*/*.pdf
          body: ''
