name: pre-release
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        documents:
          - proposal

    steps:
      - uses: actions/checkout@v2

      - name: Create links
        run: |
          chmod +x create-links.sh
          ./create-links.sh

      - name: Build documents using LaTeX (${{ matrix.documents }})
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: documents/${{ matrix.documents }}
          latexmk_use_lualatex: true
          root_file: main.tex
          extra_fonts: ../../fonts/*.ttf

      - name: Rename PDF output (${{ matrix.documents }})
        run: mv documents/${{ matrix.documents }}/main.pdf ${{ matrix.documents }}.pdf 

      - name: Upload build assets (${{ matrix.documents }})
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.documents }}
          path: ${{ matrix.documents }}.pdf

  pre-release:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - name: run latest-tag
        uses: EndBug/latest-tag@latest

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          name: Latest Build
          files: ./artifacts/*/*.pdf
          body: ''
