name: pre-release
on:
  push:
    branches:
      - main

jobs:
  build:
    uses: kurabirko/phys400/.github/workflows/build.yaml@main

  pre-release:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/download-artifact@v2
        with:
          path: ./artifacts

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          prerelease: true
          name: Latest Build
          files: ./artifacts/*/*.pdf
          body: ''
